// <auto-generated />
using System;
using MeetAgain.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetAgain.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108185114_AddValueComparers")]
    partial class AddValueComparers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetAgain.Shared.Models.Availability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MeetupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProposedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("MeetupId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("MeetAgain.Shared.Models.Friend", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GroupIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Avatar = "AJ",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 215, DateTimeKind.Utc).AddTicks(8012),
                            Email = "alice@example.com",
                            GroupIds = "",
                            Name = "Alice Johnson",
                            Phone = ""
                        },
                        new
                        {
                            Id = "2",
                            Avatar = "BS",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 215, DateTimeKind.Utc).AddTicks(8219),
                            Email = "bob@example.com",
                            GroupIds = "",
                            Name = "Bob Smith",
                            Phone = ""
                        },
                        new
                        {
                            Id = "3",
                            Avatar = "CW",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 215, DateTimeKind.Utc).AddTicks(8223),
                            Email = "carol@example.com",
                            GroupIds = "",
                            Name = "Carol White",
                            Phone = ""
                        },
                        new
                        {
                            Id = "4",
                            Avatar = "DB",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 215, DateTimeKind.Utc).AddTicks(8234),
                            Email = "david@example.com",
                            GroupIds = "",
                            Name = "David Brown",
                            Phone = ""
                        },
                        new
                        {
                            Id = "5",
                            Avatar = "ED",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 215, DateTimeKind.Utc).AddTicks(8237),
                            Email = "emma@example.com",
                            GroupIds = "",
                            Name = "Emma Davis",
                            Phone = ""
                        });
                });

            modelBuilder.Entity("MeetAgain.Shared.Models.FriendGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FriendGroups");

                    b.HasData(
                        new
                        {
                            Id = "g1",
                            Color = "#6366f1",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 216, DateTimeKind.Utc).AddTicks(3556),
                            Description = "Office colleagues",
                            MemberIds = "",
                            Name = "Work Team"
                        },
                        new
                        {
                            Id = "g2",
                            Color = "#10b981",
                            CreatedAt = new DateTime(2025, 11, 8, 18, 51, 14, 216, DateTimeKind.Utc).AddTicks(3712),
                            Description = "University buddies",
                            MemberIds = "",
                            Name = "College Friends"
                        });
                });

            modelBuilder.Entity("MeetAgain.Shared.Models.Meetup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedDates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SelectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Meetups");
                });
#pragma warning restore 612, 618
        }
    }
}
